### ISSUE TITLE
Touchpad, xbox controllers, and probably more input devices does not work

### ISSUE THREAD

**Issue by Szpadel** [htrefil/rkvm#20]
Something weird is happening when server uses touchpad or controllers.

Touchpad seams to not work at all, and controllers have messed up events (buttons do not work at all, axis work but messed up).

I'll try to debug this in spare time, but for now I want to raise awareness that those are not compatible, as I spend 2 days debugging drivers for controllers.

**Comment by rmanne** [comment]
+1 I looked into it a bit and it looks like rkvm atm only handles EV_REL and EV_KEY, but not EV_ABS (which is what Touchpads seem to use). I honestly don't have a good way of handling these either, since it doesn't look like EV_ABS can be piped to the pointer device type created (or maybe they can and I'm just missing something).

**Comment by htrefil** [comment]
Closing as this is fixed already -- current master supports abs events.
